# chart instance name overrides
nameOverride: ""
fullnameOverride: ""

# image contains the Docker image properties.
image:
  # name is the name of the Docker image, including repo and version.
  name: ghcr.io/pgdogdev/pgdog:main
  # pullPolicy specifies when to use cached version of the image. Prefer using Always
  # when using tags like "main".
  pullPolicy: Always
# port on which PgDog will run.
port: 6432
# replicas indicates how many instances of PgDog will run (HA).
replicas: 2
# openMetricsPort configures the port on which OpenMetrics (Prometheus) are exported
openMetricsPort: 9090
# prometheusPort configures the port on which Prometheus will export its metrics
# prometheusPort: 9091
# openMetricsNamespace configures the metrics namespace
openMetricsNamespace: pgdog_

# databases contains the list of database entries in pgdog.toml
# Supports all arguments from pgdog.toml. Arguments are named in camelCase format.
databases: []

# users contains the list of user entries in users.toml
# Supports all arguments from users.toml. Arguments are named in camelCase format.
users: []
