apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  # This is pgdog.toml. You can configure anything here, incl. databases.
  # Note: don't change the port value, since it's pulled from Values.
  pgdog.toml: |
    [general]
    port = {{ .Values.port }}

    [[databases]]
