apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: pgdog
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/pgdog"]
          args: ["--config", "/etc/pgdog/pgdog.toml", "--users", "/etc/secrets/pgdog/users.toml"]
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/pgdog
            - name: users
              mountPath: /etc/secrets/pgdog
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}
        - name: users
          secret:
            secretName: {{ .Values.name }}
