apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdog
  namespace: {{ .Release.Name }}
  labels:
    app: pgdog
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: pgdog
  template:
    metadata:
      labels:
        app: pgdog
    spec:
      containers:
        - name: pgdog
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/pgdog"]
          args: ["--config", "/etc/pgdog/pgdog.toml", "--users", "/etc/secrets/pgdog/users.toml"]
          ports:
            - name: pgdog
              containerPort: {{ .Values.port }}
            - name: metrics
              containerPort: {{ .Values.openMetricsPort }}
          volumeMounts:
            - name: config
              mountPath: /etc/pgdog
            - name: users
              mountPath: /etc/secrets/pgdog
        {{- if .Values.prometheusPort }}
        - name: prom
          image: prom/prometheus
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["prometheus"]
          args:
            - "--config.file=/etc/prom/prom.yml"
            - '--web.listen-address=:{{ .Values.prometheusPort | default "9091" }}'
          ports:
            - name: prom
              containerPort: {{ .Values.prometheusPort }}
          volumeMounts:
            - name: prom
              mountPath: /etc/prom
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: pgdog
        - name: users
          secret:
            secretName: pgdog
        - name: prom
          configMap:
            name: prom
