{{- define "pgdog.users" -}}
{{- range .Values.users }}
[[users]]
name = {{ .name | quote }}
database = {{ .database | quote }}
{{- if .password }}
password = {{ .password | quote }}
{{- end }}
{{- if .poolSize }}
pool_size = {{ .poolSize }}
{{- end }}
{{- if .minPoolSize }}
min_pool_size = {{ .minPoolSize }}
{{- end }}
{{- if .poolerMode }}
pooler_mode = {{ .poolerMode | quote }}
{{- end }}
{{- if .serverUser }}
server_user = {{ .serverUser | quote }}
{{- end }}
{{- if .serverPassword }}
server_password = {{ .serverPassword | quote }}
{{- end }}
{{- if .statementTimeout }}
statement_timeout = {{ .statementTimeout }}
{{- end }}
{{- if .replicationMode }}
replication_mode = {{ .replicationMode }}
{{- end }}
{{- if .idleTimeout }}
idle_timeout = {{ .idleTimeout }}
{{- end }}
{{- if .readOnly }}
read_only = {{ .readOnly }}
{{- end }}
{{- end }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: pgdog
  namespace: {{ .Release.Name }}
data:
  users.toml: {{ include "pgdog.users" . | b64enc }}
