apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: pgdog
spec:
  selector:
    app: pgdog
  ports:
    - name: pgdog
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
