apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgdog.fullname" . }}
spec:
  selector:
    app: pgdog
  ports:
    - name: pgdog
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
