apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgdog.fullname" . }}-prom
data:
  prom.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: pgdog
        scrape_interval: 15s
        static_configs:
          - targets: ['127.0.0.1:{{ .Values.openMetricsPort }}']
